### ISSUE TITLE
refactor code to deal with fields that need to be re-interpretted

### ISSUE THREAD

**Issue by hangxie** [hangxie/parquet-tools#120]
Codes to handle DECIMAL, INTERVAL and INT96 in cat and meta commands were added steadily without an high level design, the logic is spread to lots of places and hard to maintain.

Here are what's in my mind to refactor those codes:
1. test cases:
   * Cover these types:
      * DECIMAL (FIXED_LENGTH_BYTE_ARRY and BYTE_ARRAY)
      * DECIMAL (INT32 and INT64)
      * INTERVAL (FIXED_LENGTH_BYTE_ARRY)
      * INT96 (treat as timestamp only)
   * Cover field with above types in these locations:
      * top level
         * scalar
         * pointer
      * embedded
         * list element
         * map key
         * map value
2. rough idea for cat:
   1. scan schema to get all fields needs to be reinterpreted
   2. base64 string values of those fields that need to be reinterpreted
   3. JSON whole data (a single row)
   4. use gjson/sjon to retrieve fields need to be reinterpreted, convert, then assign back
3. rough idea for meta:
   1. scan schema to get all fields needs to be reinterpreted
   2. reinterpret min/max value

**Comment by hangxie-cisco** [comment]
With #123 the only thing does not work is cat on composite fields.
