### ISSUE TITLE
Is it possible to use with intranet S3 like storage?

### ISSUE THREAD

**Issue by dolzenko** [hangxie/parquet-tools#438]

**Comment by hangxie** [comment]
What exactly is "intranet S3 like storage"?

**Comment by hangxie** [comment]
> minio

Minio is a drop-in replace of S3, so this works for me:

```
docker run -d --rm --name minio -p 9000:9000 -p 9001:9001 minio/minio server /data --console-address ":9001"
export AWS_ACCESS_KEY_ID=minioadmin
export AWS_SECRET_ACCESS_KEY=minioadmin
export AWS_ENDPOINT_URL=http://127.0.0.1:9000
aws s3api create-bucket parquet-test
parquet-tools import -s testdata/csv.source -m testdata/csv.schema s3://parquet-test/minio.parquet
parquet-tools cat -f jsonl  s3://parquet-test/minio.parquet
```

I don't have experience with Ceph but seems it supports S3 API as well https://docs.ceph.com/en/latest/radosgw/s3/

**Comment by dolzenko** [comment]
I know that all these API are alike, I just wasn't sure how to pass my config. You can _probably_ put something like this in README:

> s3fs supports the standard [AWS credentials file](https://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html) stored in ${HOME}/.aws/credentials. Alternatively, s3fs supports a custom passwd file.

thnx for the great app :heart:
