### ISSUE TITLE
PARGO_PREFIX_ added to parquet fields that begin with _

### ISSUE THREAD

**Issue by pgmstream** [hangxie/parquet-tools#446]
I have started to evaluate both your parquet-tools and xitongsys for us to potentially participate in the open source project and helping with ongoing improvement. One issue I have found that does impact our overall use is the treatment of the _ character in the first character position of a parquet file field name. We are having to handle this external to this tool and the xitongsys imports. We realize this is part of the xitongsys but it does influence our decision to participate in the project. 

Cheers Peter Molloy

**Comment by hangxie** [comment]
This is by design https://github.com/xitongsys/parquet-go/issues/387 but I didn't dig into this issue too much, maybe you can open a feature to make the default prefix `PARGO_PREFIX_` configurable, if it is supported by parquet-go, I can add a CLI flag to adopt it.

**Comment by hangxie** [comment]
Seems https://github.com/xitongsys/parquet-go/issues/233 is the reason that `parquet-go` requires field names starting with uppercase (so it is exported in go).

**Comment by hangxie** [comment]
Done by https://github.com/hangxie/parquet-tools/issues/447, supports `cat`, `metadata`, and`schema` commands.
